# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.06183087 0.75558602 0.13125568 ... 0.86865329 0.74476596 0.90344307]
 [0.12263297 0.48596456 0.22006817 ... 0.84761591 0.47105412 0.19585674]
 [0.5578318  0.25807208 0.88934175 ... 0.78839458 0.73702333 0.77603962]
 ...
 [0.61923866 0.93611552 0.77547294 ... 0.45490791 0.52641055 0.31485681]
 [0.50399852 0.23676711 0.94762199 ... 0.29130387 0.72780255 0.53999105]
 [0.73611978 0.84821859 0.12824458 ... 0.78671167 0.57905456 0.87231296]]
[[0.22572999 0.29062533 0.42110876 ... 0.22564028 0.53806959 0.89750935]
 [0.01830157 0.46630492 0.01582105 ... 0.46321305 0.50701504 0.76783452]
 [0.7244812  0.62293197 0.4747977  ... 0.95632362 0.45010369 0.26201892]
 ...
 [0.5916122  0.17000534 0.02339895 ... 0.92221656 0.50977413 0.14637879]
 [0.89726319 0.34713641 0.62363424 ... 0.78210948 0.41542209 0.12624408]
 [0.43985476 0.32998944 0.29354618 ... 0.02678604 0.66158774 0.63652143]]


Без использования numpy:

In [3]:
def mult(a, b):
    n = len(a)
    result = [[0] * n for _ in range(n)]

    for i in range(n):
        for j in range(n):
            for k in range(n):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [4]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 708 ms, sys: 2.88 ms, total: 711 ms
Wall time: 720 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.69 ms, sys: 878 µs, total: 2.57 ms
Wall time: 8.1 ms


In [7]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.495692458775011e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.02521615 0.55987293 0.81485451] [0.76390521 0.58276967 0.74833468]


In [10]:
# без Numpy
def scalar_product(a,b):
    s = 0
    s = sum([a[i]*b[i] for i in range(len(a))])
    return s

In [11]:
# с использованием Numpy
def np_scalar_product(a,b):
    s = 0
    s = np.dot(a, b)
    return s

In [13]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 27 µs, sys: 4 µs, total: 31 µs
Wall time: 34.6 µs
CPU times: user 52 µs, sys: 8 µs, total: 60 µs
Wall time: 63.9 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:**

Методы NumPy оказываются эффективнее по нескольким причинам. Во-первых, NumPy написан на языке программирования C, что позволяет значительно ускорить вычисления по сравнению с использованием чистого Python. Язык C является низкоуровневым и позволяет более эффективно использовать аппаратные возможности компьютера.

Во-вторых, NumPy использует векторизацию, что позволяет выполнять операции над массивами данных целиком, а не поэлементно. Векторизация позволяет использовать оптимизированные аппаратные инструкции для выполнения операций над массивами, ускоряя обработку данных. Например, при выполнении математических операций над массивами NumPy использует встроенные функции библиотеки BLAS (Basic Linear Algebra Subprograms), которые оптимизированы для работы с матрицами и векторами.

Кроме того, методы NumPy обеспечивают более эффективное использование памяти. Вместо создания новых объектов с каждой операцией, NumPy позволяет выполнять операции в place, т.е. непосредственно внутри исходного массива, что значительно снижает накладные расходы на создание и удаление объектов.

Скорость вычислений в NumPy зависит от нескольких факторов, таких как размеры данных, сложность операций и оптимизации аппаратной платформы. Однако общим правилом является то, что использование методов NumPy значительно ускоряет вычисления по сравнению с чистым Python. Векторизация операций и оптимизация использования памяти позволяют выполнить большие вычислительные задачи в несколько раз быстрее, чем с использованием стандартных средств Python.

------------------

### Задание 3
Напишите функцию, которая находит сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [14]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  arr = np.array(a)
  n = arr.shape[0]
  res = 0

  for i in range(n):
      if arr[i, i] % 2 == 0:
          res += arr[i, i]
  return res

In [15]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[9, 2, 3, 1, 3],
       [1, 8, 8, 4, 3],
       [2, 5, 2, 2, 6],
       [8, 2, 8, 6, 1],
       [8, 9, 8, 3, 6]])

In [16]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 53 µs, sys: 7 µs, total: 60 µs
Wall time: 65.8 µs


22

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [17]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = np.cumsum(A, axis=1)
    return result

In [18]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[1.11143256e-01 5.17643514e-01 5.54512028e-01 9.78141360e-01
 6.42406145e-02 5.09114631e-01 9.99114117e-02 2.98806641e-01
 2.95543114e-01 6.24690792e-01 7.13698859e-01 5.03670521e-01
 4.22213840e-02 5.46084408e-01 2.08101549e-01 9.46449768e-01
 3.25452950e-01 9.13050804e-01 8.29111492e-01 5.44524346e-02
 6.25084828e-01 7.92990466e-01 5.91263061e-01 8.68824610e-01
 4.62351919e-01 6.36090066e-01 5.73891359e-01 7.45402966e-01
 5.00266279e-01 7.19002514e-01 9.23452023e-01 5.64842260e-01
 2.53148140e-01 8.96043193e-01 1.34968013e-02 2.73312463e-01
 4.87822418e-01 2.72485969e-01 5.86444753e-01 8.20849117e-01
 1.38423707e-01 6.89382354e-01 8.69217531e-01 8.85673347e-01
 6.35110801e-01 3.00064165e-01 8.31196371e-01 2.50252855e-01
 6.38549034e-01 4.80501298e-02 4.81957339e-01 5.83298019e-01
 9.67250679e-01 7.33663252e-02 9.28826440e-03 3.41555451e-02
 5.44471417e-01 2.56151186e-01 1.65197393e-01 4.75520213e-01
 3.53536264e-01 7.50638159e-01 2.07624123e-01 2.89342701e-01
 1.66996372e-01 2.947208

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [19]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    elements = []
    counts = []

    current_element = a[0]
    current_count = 1

    for i in range(1, len(a)):
        if a[i] == current_element:
            current_count += 1
        else:
            elements.append(current_element)
            counts.append(current_count)
            current_element = a[i]
            current_count = 1

    elements.append(current_element)
    counts.append(current_count)

    result = np.array(elements), np.array(counts)
    return result

In [20]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 46 µs, sys: 0 ns, total: 46 µs
Wall time: 50.5 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [21]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    transformed_X = X.copy()

    transformed_X[1::2] = a

    transformed_X[::2] = transformed_X[::2] ** 3

    reversed_transformed_X = transformed_X[::-1]

    result = np.concatenate((X, reversed_transformed_X))

    return result

In [22]:
X = np.array([i for i in range(1, 10, 2)])
print(X)
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(np_transformation(X, 5))

[1 3 5 7 9]
CPU times: user 0 ns, sys: 307 µs, total: 307 µs
Wall time: 841 µs
[  1   3   5   7   9 729   5 125   5   1]
